http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      middlewares:
        - security-headers  # Aplicar middleware de segurança
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "dev.local"
            sans:
              - "*.dev.local"
          - main: "dev.localhost"
            sans:
              - "*.dev.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
    - certFile: "/etc/certs/localhost-cert.pem"
      keyFile: "/etc/certs/localhost-key.pem"