global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

# providers:
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: reverse-proxy
    watch: true
  # docker:
  #   endpoint: "unix:///var/run/docker.sock"
  #   watch: true
  #   exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
log:
  level: DEBUG
# log:
#   level: INFO
#   format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
