services:

  nginx:
    image: 'nginx:1.25-alpine'
    container_name: meusite-nginx
    expose:
      - '80'
      - '443'
    depends_on:
      - phpfpm
    networks:
      - sr-reverse-proxy
      - meusite-net
    environment:
      - NGINX_HOST=meusite.com
      - SITE_ID=meusite
    volumes:
      - './system:/var/www/html'
      - './config/nginx/server.conf:/etc/nginx/conf.d/common/_server.conf:ro'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=sr-reverse-proxy"
      - "traefik.http.routers.meusite.rule=Host(`meusite.com`)"
      - "traefik.http.routers.meusite.tls=true"
      - "traefik.http.routers.meusite.service=meusite"
      - "traefik.http.services.meusite.loadbalancer.server.port=80"  
      - "traefik.http.routers.meusite.middlewares=meusite-prefix"
      - "traefik.http.middlewares.meusite-prefix.stripprefix.prefixes=/meusite"
    
  phpfpm:
    build:
      context: .containers
      dockerfile: php-fpm
      args:
        PHP_IMAGE: php:8.2-fpm
        CALLING_USER: kenji
        CALLING_UID: 1000
    image: php:8.2-fpm-kenji
    container_name: meusite-phpfpm
    networks:
      - meusite-net
      - sr-public_network
    volumes:
      - './system:/var/www/html'
      - './config/php-fpm/wp-cli.local.yml:/var/www/.wp-cli/config.yml:ro'
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1 
      - PHP_OPCACHE_REVALIDATE_FREQ=0
    user: "1000:1000"

networks:
  sr-reverse-proxy:
    external: true
    name: sr-reverse-proxy
  meusite-net:
    driver: bridge
  sr-public_network:
    external: true
    name: sr-public_network 