services:

  nginx:
    image: 'nginx:1.25-alpine'
    container_name: <SITE_NAME>-nginx
    expose:
      - '80'
      - '443'
    depends_on:
      - phpfpm
    networks:
      - reverse-proxy
    # environment:
    #   WORDPRESS_DB_HOST: mariadb
    #   WORDPRESS_DB_NAME: wordpress_site1
    #   WORDPRESS_DB_USER: wordpress_site1
    #   WORDPRESS_DB_PASSWORD: wordpress_site1
    volumes:
      - './system:/var/www/html:cached'
      - './config/nginx/server.conf:/etc/nginx/conf.d/common/_server.conf:cached'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.<labels>.rule=Host(`<SITE_URL>`)"
      - "traefik.http.routers.<labels>.tls=true"
      - "traefik.http.services.<labels>.loadbalancer.server.port=80"  
      - "traefik.http.routers.<labels>.middlewares=<labels>-prefix"
      - "traefik.http.middlewares.<labels>-prefix.stripprefix.prefixes=/<labels>"
    
  phpfpm:
    image: <PHP_IMAGE>-<USER_NAME>
    container_name: <SITE_NAME>-phpfpm
    networks:
      - reverse-proxy
    volumes:
      - './system:/var/www/html:cached'
      - './config/php-fpm/wp-cli.local.yml:/var/www/.wp-cli/config.yml:cached'
      # - './config/php-fpm/docker-php-ext-xdebug.ini:/etc/php/8.2/fpm/conf.d/docker-php-ext-xdebug.ini:cached'
    # cap_add:
    #   - SYS_PTRACE
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0 
      # ENABLE_XDEBUG: 'true'
      # PHP_IDE_CONFIG: serverName=negocios-test
    user: "1000:1000"
    build:
      dockerfile: php-fpm
      context: .containers
      args:
        PHP_IMAGE: <PHP_IMAGE>
        CALLING_USER: <USER_NAME>
        CALLING_UID: 1000
networks:
  reverse-proxy:
    external: true
